name: demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  font_awesome_flutter: any
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: 'Emoji'
      fonts:
        - asset: assets/fonts/FacebookEmoji.ttf
    - family: 'Bangla'
      fonts:
        - asset: assets/fonts/NikoshGrameen.ttf
    - family: "Montserrat"
      fonts:
        - asset: "assets/fonts/Montserrat/Montserrat-Black.ttf"
          weight: 900
        - asset: "assets/fonts/Montserrat/Montserrat-BlackItalic.ttf"
          style: italic
          weight: 900
        - asset: "assets/fonts/Montserrat/Montserrat-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Montserrat/Montserrat-BoldItalic.ttf"
          style: italic
          weight: 700
        - asset: "assets/fonts/Montserrat/Montserrat-ExtraBold.ttf"
          weight: 700
        - asset: "assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf"
          style: italic
          weight: 700
        - asset: "assets/fonts/Montserrat/Montserrat-ExtraLight.ttf"
          weight: 200
        - asset: "assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf"
          style: italic
          weight: 200
        - asset: "assets/fonts/Montserrat/Montserrat-Italic.ttf"
          style: italic
        - asset: "assets/fonts/Montserrat/Montserrat-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Montserrat/Montserrat-LightItalic.ttf"
          style: italic
          weight: 300
        - asset: "assets/fonts/Montserrat/Montserrat-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Montserrat/Montserrat-MediumItalic.ttf"
          style: italic
          weight: 500
        - asset: "assets/fonts/Montserrat/Montserrat-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Montserrat/Montserrat-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf"
          style: italic
          weight: 600
        - asset: "assets/fonts/Montserrat/Montserrat-Thin.ttf"
          weight: 100
        - asset: "assets/fonts/Montserrat/Montserrat-ThinItalic.ttf"
          style: italic
          weight: 100
    - family: 'Lobster'
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf
        - asset: assets/fonts/LobsterTwo-Italic.ttf
          style: italic
        - asset: assets/fonts/LobsterTwo-Bold.ttf
          weight: 600
        - asset: assets/fonts/LobsterTwo-BoldItalic.ttf
          weight: 600
          style: italic
    - family: "SCP"
      fonts:
        - asset: "assets/fonts/SCP/SourceCodePro-Black.ttf"
          weight: 900
        - asset: "assets/fonts/SCP/SourceCodePro-BlackItalic.ttf"     
          style: italic
          weight: 900
        - asset: "assets/fonts/SCP/SourceCodePro-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/SCP/SourceCodePro-BoldItalic.ttf"      
          style: italic
          weight: 700
        - asset: "assets/fonts/SCP/SourceCodePro-ExtraLight.ttf"      
          weight: 200
        - asset: "assets/fonts/SCP/SourceCodePro-ExtraLightItalic.ttf"
          style: italic
          weight: 200
        - asset: "assets/fonts/SCP/SourceCodePro-Italic.ttf"
          style: italic
        - asset: "assets/fonts/SCP/SourceCodePro-Light.ttf"
          weight: 300
        - asset: "assets/fonts/SCP/SourceCodePro-LightItalic.ttf"     
          style: italic
          weight: 300
        - asset: "assets/fonts/SCP/SourceCodePro-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/SCP/SourceCodePro-MediumItalic.ttf"    
          style: italic
          weight: 500
        - asset: "assets/fonts/SCP/SourceCodePro-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/SCP/SourceCodePro-SemiBold.ttf"        
          weight: 600
        - asset: "assets/fonts/SCP/SourceCodePro-SemiBoldItalic.ttf"  
          style: italic
          weight: 600
    - family: "MRB"
      fonts:
        - asset: "assets/fonts/Roboto/Roboto-Black.ttf"
          weight: 900
        - asset: "assets/fonts/Roboto/Roboto-BlackItalic.ttf"
          style: italic
          weight: 900
        - asset: "assets/fonts/Roboto/Roboto-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Roboto/Roboto-BoldItalic.ttf"
          style: italic
          weight: 700
        - asset: "assets/fonts/Roboto/Roboto-Italic.ttf"
          style: italic
        - asset: "assets/fonts/Roboto/Roboto-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Roboto/Roboto-LightItalic.ttf"
          style: italic
          weight: 300
        - asset: "assets/fonts/Roboto/Roboto-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Roboto/Roboto-MediumItalic.ttf"
          style: italic
          weight: 500
        - asset: "assets/fonts/Roboto/Roboto-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Roboto/Roboto-Thin.ttf"
          weight: 100
        - asset: "assets/fonts/Roboto/Roboto-ThinItalic.ttf"
          style: italic
          weight: 100
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
